### ISSUE TITLE
Encoding fail: size mismatch for inv_pool.4.bias

### ISSUE THREAD

**Issue by ichlubna** [I2-Multimedia-Lab/IPDAE#1]
Hello,
thanks for sharing your code! I have tried to use it with the recommended data but the encoder crashes with an exception.
Running as:

python ./compress.py  'ModelNet40_pc_01_8192p/airplane/test/*.ply' './test' './model/K256' --K 25
And getting:

```
Traceback (most recent call last):
  File "/home/ichlubna/Workspace/IPDAE/./compress.py", line 56, in <module>
    ae.load_state_dict(torch.load(NET_PATH))
  File "/usr/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AE:
	size mismatch for inv_pool.4.weight: copying a param with shape torch.Size([16384, 1024]) from checkpoint, the shape in current model is torch.Size([1536, 1024]).
	size mismatch for inv_pool.4.bias: copying a param with shape torch.Size([16384]) from checkpoint, the shape in current model is torch.Size([1536]).
```
Would you please help me to solve this?
Thanks

**Comment by youkangGG** [comment]
It seems like you're using an inapproprate parameter K that is inconsistent with the model.

Make sure you use a consistent K value like this:

`
python ./compress.py 'ModelNet40_pc_01_8192p/airplane/test/*.ply' './test' './model/K256' --K 256
`

Instead of assigning --K 25 for './model/K256', since **each model is boundled to a fixed K value** in this project.

I hope this can solve your problem, thank you for your interest in our work😀

**Comment by ichlubna** [comment]
Thank you so much! This is the right solution!
